name: MLOps-Project

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{secrets.PROJECT_ID}}
    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Test
        run: |
          python -m pytest

      - name: Set up gcloud CLI
        uses: 'google-github-actions/auth@v1'
        with:
          credential_json: ${{secrets.CREDENTIALS_JSON}}
          service_account_key: ${{secrets.SERVICE_ACCOUNT}}
          export_default_credentials: true

      - name: Build the container image
        run: |
          docker build -t us-central1-docker.pkg.dev/${PROJECT_ID}/mlops/fastapi:latest .

      - name: Push image to Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker push us-central1-docker.pkg.dev/${PROJECT_ID}/mlops/fastapi:latest

      - name: Deploy to Cloud Run 
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: fastapi 
          image: us-central1-docker.pkg.dev/${{secrets.PROJECT_ID}}/mlops/fastapi:latest
          region: us-central1
          platform: managed
          allow-unauthenticated: true
          service_account_key: ${{secrets.SERVICE_ACCOUNT }}
          project_id:  ${{secrets.PROJECT_ID }}
          credential_json: ${{secrets.CREDENTIALS_JSON }}
